name: Briefly
options:
  bundleIdPrefix: com.briefly
  deploymentTarget:
    iOS: "17.0"
packages:
  Supabase:
    url: https://github.com/supabase-community/supabase-swift.git
    from: 2.0.0
schemes:
  Briefly:
    build:
      targets:
        Briefly: all
    run:
      config: Debug
  BrieflyTests:
    build:
      targets:
        Briefly: all
        BrieflyTests: all
    test:
      config: Debug
      targets:
        - BrieflyTests
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: Config/Debug.xcconfig
  Release: Config/Release.xcconfig
settings:
  BASE_SDK: iphoneos
  SWIFT_VERSION: 5.0
  IPHONEOS_DEPLOYMENT_TARGET: "17.0"
targets:
  Briefly:
    type: application
    platform: iOS
    sources:
      - path: Briefly
    info:
      path: Briefly/Resources/Info.plist
    dependencies:
      - package: Supabase
    configFiles:
      Debug: Config/Debug.xcconfig
      Release: Config/Release.xcconfig
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.briefly.app
      TARGETED_DEVICE_FAMILY: "1,2"
      SUPPORTS_MACCATALYST: NO
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  BrieflyTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BrieflyTests
    configFiles:
      Debug: Config/Debug.xcconfig
      Release: Config/Release.xcconfig
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Briefly
