name: Briefly
options:
  bundleIdPrefix: com.briefly
  deploymentTarget:
    iOS: "17.0"
configs:
  Debug: debug
  Release: release
settings:
  BASE_SDK: iphoneos
  SWIFT_VERSION: 5.0
  IPHONEOS_DEPLOYMENT_TARGET: "17.0"
targets:
  Briefly:
    type: application
    platform: iOS
    sources:
      - path: Briefly
    info:
      path: Briefly/Resources/Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.briefly.app
      TARGETED_DEVICE_FAMILY: 1
      SUPPORTS_MACCATALYST: NO
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  BrieflyTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BrieflyTests
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Briefly
